///|
#external
type DOMRect

///|
pub extern "js" fn DOMRect::left(self : DOMRect) -> Double = "(self) => self.left"

///|
pub extern "js" fn DOMRect::right(self : DOMRect) -> Double = "(self) => self.right"

///|
pub extern "js" fn DOMRect::top(self : DOMRect) -> Double = "(self) => self.top"

///|
pub extern "js" fn DOMRect::bottom(self : DOMRect) -> Double = "(self) => self.bottom"

///|
pub extern "js" fn DOMRect::width(self : DOMRect) -> Double = "(self) => self.width"

///|
pub extern "js" fn DOMRect::height(self : DOMRect) -> Double = "(self) => self.height"
